import type { Metadata } from "next";
import { Roboto,Dosis } from 'next/font/google'
import "./globals.css";

// const roboto = Roboto({
//   weight: ["100","300","400","500","700","900"]
// })
//
const dosis = Dosis({
    weight: ["200","300","400","500","700","800"]
})

export const metadata: Metadata = {
    title: "Hatke Global Logistics",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${dosis.className} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}