import type {Metadata} from "next";
import {Dosis} from 'next/font/google'
import "./globals.css";
import { Provider } from "@/components/ui/provider"
import {Theme} from "@chakra-ui/react";

const dosis = Dosis({
    weight: ["200","300","400","500","700","800"],
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Hatke Global Logistics",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${dosis.className} antialiased`}
        >
        <Provider>
            <Theme appearance="light">
            {children}
            </Theme>
        </Provider>
        </body>
        </html>
    );
}